minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - ts-airtable
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - ua-parser-js@1.0.41

allowBuilds:
  sharp: true

packages:
  - .
