minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - ts-airtable

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - ua-parser-js@1.0.41

shellEmulator: true

packages:
  - .

allowBuilds:
  sharp: true
