name: Auto Tag PR based on file paths

on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          json: true

      - name: Add labels based on changed files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const changedFiles = ${{ steps.changed-files.outputs.all_changed_files }};
            const labelMap = {
              "src/app/": "app-router",
              "src/components/": "components",
              "src/hooks/": "hooks",
              "src/lib/": "lib",
              "src/utils/": "utils",
              "src/styles/": "styles",
              "src/types/": "types",
              "public/": "public-assets",
              "package.json": "deps",
              "yarn.lock": "deps"
            };

            const labelsToAdd = new Set();

            changedFiles.forEach(file => {
              for (const [path, label] of Object.entries(labelMap)) {
                if (file.startsWith(path)) {
                  labelsToAdd.add(label);
                }
              }
            });

            if (labelsToAdd.size > 0) {
              const { owner, repo, number } = context.issue;
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: number,
                labels: Array.from(labelsToAdd)
              });
            }
