name: Tag PR Size
on: pull_request_target
jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          IGNORED: |
            pnpm-lock.yaml
            package-lock.json
            .yarn/*
            yarn.lock
            .pnp.*
            dist/**
            build/**
            .cache/**
            .vscode/**
            .github/**
            .gitignore
        with:
          sizes: >
            {
              "0": "XS",
              "50": "S",
              "300": "M",
              "1000": "L",
              "1500": "XL",
              "2500": "XXL"
            }
